//  Copyright (c) 2025 Feng Yang
//
//  I am making my contributions/submissions to this project solely in my
//  personal capacity and am not conveying any rights to any intellectual
//  property of any third parties.

#include <nanobind/nanobind.h>
#include <nanobind/stl/string.h>
#include <nanobind/stl/vector.h>
#include <nanobind/stl/map.h>
#include <rtabmap/core/Statistics.h>
#include "cv_typecaster.h"

namespace nb = nanobind;
using namespace nb::literals;
using namespace rtabmap;

void bindStatistics(nb::module_ &m) {
    nb::class_<Statistics>(m, "Statistics")
            .def(nb::init<>())
            .def_static("kLoopId", &Statistics::kLoopId)
            .def_static("kLoopRejectedHypothesis", &Statistics::kLoopRejectedHypothesis)
            .def_static("kLoopAccepted_hypothesis_id", &Statistics::kLoopAccepted_hypothesis_id)
            .def_static("kLoopSuppressed_hypothesis_id", &Statistics::kLoopSuppressed_hypothesis_id)
            .def_static("kLoopHighest_hypothesis_id", &Statistics::kLoopHighest_hypothesis_id)
            .def_static("kLoopHighest_hypothesis_value", &Statistics::kLoopHighest_hypothesis_value)
            .def_static("kLoopVp_hypothesis", &Statistics::kLoopVp_hypothesis)
            .def_static("kLoopReactivate_id", &Statistics::kLoopReactivate_id)
            .def_static("kLoopHypothesis_ratio", &Statistics::kLoopHypothesis_ratio)
            .def_static("kLoopHypothesis_reactivated", &Statistics::kLoopHypothesis_reactivated)
            .def_static("kLoopMap_id", &Statistics::kLoopMap_id)
            .def_static("kLoopVisual_words", &Statistics::kLoopVisual_words)
            .def_static("kLoopVisual_inliers", &Statistics::kLoopVisual_inliers)
            .def_static("kLoopVisual_inliers_ratio", &Statistics::kLoopVisual_inliers_ratio)
            .def_static("kLoopVisual_matches", &Statistics::kLoopVisual_matches)
            .def_static("kLoopDistance_since_last_loc", &Statistics::kLoopDistance_since_last_loc)
            .def_static("kLoopLast_id", &Statistics::kLoopLast_id)
            .def_static("kLoopOptimization_max_error", &Statistics::kLoopOptimization_max_error)
            .def_static("kLoopOptimization_max_error_ratio", &Statistics::kLoopOptimization_max_error_ratio)
            .def_static("kLoopOptimization_max_ang_error", &Statistics::kLoopOptimization_max_ang_error)
            .def_static("kLoopOptimization_max_ang_error_ratio", &Statistics::kLoopOptimization_max_ang_error_ratio)
            .def_static("kLoopOptimization_error", &Statistics::kLoopOptimization_error)
            .def_static("kLoopOptimization_iterations", &Statistics::kLoopOptimization_iterations)
            .def_static("kLoopLinear_variance", &Statistics::kLoopLinear_variance)
            .def_static("kLoopAngular_variance", &Statistics::kLoopAngular_variance)
            .def_static("kLoopLandmark_detected", &Statistics::kLoopLandmark_detected)
            .def_static("kLoopLandmark_detected_node_ref", &Statistics::kLoopLandmark_detected_node_ref)
            .def_static("kLoopVisual_inliers_mean_dist", &Statistics::kLoopVisual_inliers_mean_dist)
            .def_static("kLoopVisual_inliers_distribution", &Statistics::kLoopVisual_inliers_distribution)
            .def_static("kLoopProximity_links_cleared", &Statistics::kLoopProximity_links_cleared)
            .def_static("kLoopOdom_correction_norm", &Statistics::kLoopOdom_correction_norm)
            .def_static("kLoopOdom_correction_angle", &Statistics::kLoopOdom_correction_angle)
            .def_static("kLoopOdom_correction_x", &Statistics::kLoopOdom_correction_x)
            .def_static("kLoopOdom_correction_y", &Statistics::kLoopOdom_correction_y)
            .def_static("kLoopOdom_correction_z", &Statistics::kLoopOdom_correction_z)
            .def_static("kLoopOdom_correction_roll", &Statistics::kLoopOdom_correction_roll)
            .def_static("kLoopOdom_correction_pitch", &Statistics::kLoopOdom_correction_pitch)
            .def_static("kLoopOdom_correction_yaw", &Statistics::kLoopOdom_correction_yaw)
            .def_static("kLoopMapToOdom_norm", &Statistics::kLoopMapToOdom_norm)
            .def_static("kLoopMapToOdom_angle", &Statistics::kLoopMapToOdom_angle)
            .def_static("kLoopMapToOdom_x", &Statistics::kLoopMapToOdom_x)
            .def_static("kLoopMapToOdom_y", &Statistics::kLoopMapToOdom_y)
            .def_static("kLoopMapToOdom_z", &Statistics::kLoopMapToOdom_z)
            .def_static("kLoopMapToOdom_roll", &Statistics::kLoopMapToOdom_roll)
            .def_static("kLoopMapToOdom_yaw", &Statistics::kLoopMapToOdom_yaw)
            .def_static("kLoopMapToOdom_pitch", &Statistics::kLoopMapToOdom_pitch)
            .def_static("kLoopMapToBase_x", &Statistics::kLoopMapToBase_x)
            .def_static("kLoopMapToBase_y", &Statistics::kLoopMapToBase_y)
            .def_static("kLoopMapToBase_z", &Statistics::kLoopMapToBase_z)
            .def_static("kLoopMapToBase_roll", &Statistics::kLoopMapToBase_roll)
            .def_static("kLoopMapToBase_pitch", &Statistics::kLoopMapToBase_pitch)
            .def_static("kLoopMapToBase_yaw", &Statistics::kLoopMapToBase_yaw)
            .def_static("kLoopMapToBase_lin_std", &Statistics::kLoopMapToBase_lin_std)
            .def_static("kLoopMapToBase_lin_var", &Statistics::kLoopMapToBase_lin_var)
            .def_static("kProximityTime_detections", &Statistics::kProximityTime_detections)
            .def_static("kProximitySpace_last_detection_id", &Statistics::kProximitySpace_last_detection_id)
            .def_static("kProximitySpace_paths", &Statistics::kProximitySpace_paths)
            .def_static("kProximitySpace_visual_paths_checked", &Statistics::kProximitySpace_visual_paths_checked)
            .def_static("kProximitySpace_scan_paths_checked", &Statistics::kProximitySpace_scan_paths_checked)
            .def_static("kProximitySpace_detections_added_visually", &Statistics::kProximitySpace_detections_added_visually)
            .def_static("kProximitySpace_detections_added_icp_multi", &Statistics::kProximitySpace_detections_added_icp_multi)
            .def_static("kProximitySpace_detections_added_icp_global", &Statistics::kProximitySpace_detections_added_icp_global)
            .def_static("kNeighborLinkRefiningAccepted", &Statistics::kNeighborLinkRefiningAccepted)
            .def_static("kNeighborLinkRefiningInliers", &Statistics::kNeighborLinkRefiningInliers)
            .def_static("kNeighborLinkRefiningICP_inliers_ratio", &Statistics::kNeighborLinkRefiningICP_inliers_ratio)
            .def_static("kNeighborLinkRefiningICP_rotation", &Statistics::kNeighborLinkRefiningICP_rotation)
            .def_static("kNeighborLinkRefiningICP_translation", &Statistics::kNeighborLinkRefiningICP_translation)
            .def_static("kNeighborLinkRefiningICP_complexity", &Statistics::kNeighborLinkRefiningICP_complexity)
            .def_static("kNeighborLinkRefiningVariance", &Statistics::kNeighborLinkRefiningVariance)
            .def_static("kNeighborLinkRefiningPts", &Statistics::kNeighborLinkRefiningPts)
            .def_static("kMemoryWorking_memory_size", &Statistics::kMemoryWorking_memory_size)
            .def_static("kMemoryShort_time_memory_size", &Statistics::kMemoryShort_time_memory_size)
            .def_static("kMemoryDatabase_memory_used", &Statistics::kMemoryDatabase_memory_used)
            .def_static("kMemorySignatures_removed", &Statistics::kMemorySignatures_removed)
            .def_static("kMemoryImmunized_globally", &Statistics::kMemoryImmunized_globally)
            .def_static("kMemoryImmunized_locally", &Statistics::kMemoryImmunized_locally)
            .def_static("kMemoryImmunized_locally_max", &Statistics::kMemoryImmunized_locally_max)
            .def_static("kMemorySignatures_retrieved", &Statistics::kMemorySignatures_retrieved)
            .def_static("kMemoryImages_buffered", &Statistics::kMemoryImages_buffered)
            .def_static("kMemoryRehearsal_sim", &Statistics::kMemoryRehearsal_sim)
            .def_static("kMemoryRehearsal_id", &Statistics::kMemoryRehearsal_id)
            .def_static("kMemoryRehearsal_merged", &Statistics::kMemoryRehearsal_merged)
            .def_static("kMemoryLocal_graph_size", &Statistics::kMemoryLocal_graph_size)
            .def_static("kMemoryOdom_cache_poses", &Statistics::kMemoryOdom_cache_poses)
            .def_static("kMemoryOdom_cache_links", &Statistics::kMemoryOdom_cache_links)
            .def_static("kMemorySmall_movement", &Statistics::kMemorySmall_movement)
            .def_static("kMemoryFast_movement", &Statistics::kMemoryFast_movement)
            .def_static("kMemoryNew_landmark", &Statistics::kMemoryNew_landmark)
            .def_static("kMemoryOdometry_variance_ang", &Statistics::kMemoryOdometry_variance_ang)
            .def_static("kMemoryOdometry_variance_lin", &Statistics::kMemoryOdometry_variance_lin)
            .def_static("kMemoryDistance_travelled", &Statistics::kMemoryDistance_travelled)
            .def_static("kMemoryRAM_usage", &Statistics::kMemoryRAM_usage)
            .def_static("kMemoryRAM_estimated", &Statistics::kMemoryRAM_estimated)
            .def_static("kMemoryTriangulated_points", &Statistics::kMemoryTriangulated_points)
            .def_static("kMemoryClosest_node_distance", &Statistics::kMemoryClosest_node_distance)
            .def_static("kMemoryClosest_node_angle", &Statistics::kMemoryClosest_node_angle)

            .def_static("kTimingMemory_update", &Statistics::kTimingMemory_update)
            .def_static("kTimingNeighbor_link_refining", &Statistics::kTimingNeighbor_link_refining)
            .def_static("kTimingProximity_by_time", &Statistics::kTimingProximity_by_time)
            .def_static("kTimingProximity_by_space_search", &Statistics::kTimingProximity_by_space_search)
            .def_static("kTimingProximity_by_space_visual", &Statistics::kTimingProximity_by_space_visual)
            .def_static("kTimingProximity_by_space", &Statistics::kTimingProximity_by_space)
            .def_static("kTimingCleaning_neighbors", &Statistics::kTimingCleaning_neighbors)
            .def_static("kTimingReactivation", &Statistics::kTimingReactivation)
            .def_static("kTimingAdd_loop_closure_link", &Statistics::kTimingAdd_loop_closure_link)
            .def_static("kTimingMap_optimization", &Statistics::kTimingMap_optimization)
            .def_static("kTimingLikelihood_computation", &Statistics::kTimingLikelihood_computation)
            .def_static("kTimingPosterior_computation", &Statistics::kTimingPosterior_computation)
            .def_static("kTimingHypotheses_creation", &Statistics::kTimingHypotheses_creation)
            .def_static("kTimingHypotheses_validation", &Statistics::kTimingHypotheses_validation)
            .def_static("kTimingStatistics_creation", &Statistics::kTimingStatistics_creation)
            .def_static("kTimingMemory_cleanup", &Statistics::kTimingMemory_cleanup)
            .def_static("kTimingTotal", &Statistics::kTimingTotal)
            .def_static("kTimingForgetting", &Statistics::kTimingForgetting)
            .def_static("kTimingJoining_trash", &Statistics::kTimingJoining_trash)
            .def_static("kTimingEmptying_trash", &Statistics::kTimingEmptying_trash)
            .def_static("kTimingFinalizing_statistics", &Statistics::kTimingFinalizing_statistics)
            .def_static("kTimingRAM_estimation", &Statistics::kTimingRAM_estimation)

            .def_static("kTimingMemPre_update", &Statistics::kTimingMemPre_update)
            .def_static("kTimingMemSignature_creation", &Statistics::kTimingMemSignature_creation)
            .def_static("kTimingMemRehearsal", &Statistics::kTimingMemRehearsal)
            .def_static("kTimingMemKeypoints_detection", &Statistics::kTimingMemKeypoints_detection)
            .def_static("kTimingMemSubpixel", &Statistics::kTimingMemSubpixel)
            .def_static("kTimingMemStereo_correspondences", &Statistics::kTimingMemStereo_correspondences)
            .def_static("kTimingMemDescriptors_extraction", &Statistics::kTimingMemDescriptors_extraction)
            .def_static("kTimingMemRectification", &Statistics::kTimingMemRectification)
            .def_static("kTimingMemKeypoints_3D", &Statistics::kTimingMemKeypoints_3D)
            .def_static("kTimingMemKeypoints_3D_motion", &Statistics::kTimingMemKeypoints_3D_motion)
            .def_static("kTimingMemJoining_dictionary_update", &Statistics::kTimingMemJoining_dictionary_update)
            .def_static("kTimingMemAdd_new_words", &Statistics::kTimingMemAdd_new_words)
            .def_static("kTimingMemCompressing_data", &Statistics::kTimingMemCompressing_data)
            .def_static("kTimingMemPost_decimation", &Statistics::kTimingMemPost_decimation)
            .def_static("kTimingMemScan_filtering", &Statistics::kTimingMemScan_filtering)
            .def_static("kTimingMemOccupancy_grid", &Statistics::kTimingMemOccupancy_grid)
            .def_static("kTimingMemMarkers_detection", &Statistics::kTimingMemMarkers_detection)

            .def_static("kKeypointDictionary_size", &Statistics::kKeypointDictionary_size)
            .def_static("kKeypointCurrent_frame", &Statistics::kKeypointCurrent_frame)
            .def_static("kKeypointIndexed_words", &Statistics::kKeypointIndexed_words)
            .def_static("kKeypointIndex_memory_usage", &Statistics::kKeypointIndex_memory_usage)

            .def_static("kGtTranslational_rmse", &Statistics::kGtTranslational_rmse)
            .def_static("kGtTranslational_mean", &Statistics::kGtTranslational_mean)
            .def_static("kGtTranslational_median", &Statistics::kGtTranslational_median)
            .def_static("kGtTranslational_std", &Statistics::kGtTranslational_std)
            .def_static("kGtTranslational_min", &Statistics::kGtTranslational_min)
            .def_static("kGtTranslational_max", &Statistics::kGtTranslational_max)
            .def_static("kGtRotational_rmse", &Statistics::kGtRotational_rmse)
            .def_static("kGtRotational_mean", &Statistics::kGtRotational_mean)
            .def_static("kGtRotational_median", &Statistics::kGtRotational_median)
            .def_static("kGtRotational_std", &Statistics::kGtRotational_std)
            .def_static("kGtRotational_min", &Statistics::kGtRotational_min)
            .def_static("kGtRotational_max", &Statistics::kGtRotational_max)
            .def_static("kGtLocalization_linear_error", &Statistics::kGtLocalization_linear_error)
            .def_static("kGtLocalization_angular_error", &Statistics::kGtLocalization_angular_error)

    .def_static("defaultData", &Statistics::defaultData)
    .def_static("serializeData", &Statistics::serializeData)
    .def_static("deserializeData", &Statistics::deserializeData)

    .def("addStatistic", &Statistics::addStatistic)
    .def("setExtended", &Statistics::setExtended)
    .def("setRefImageId", &Statistics::setRefImageId)
    .def("setRefImageMapId", &Statistics::setRefImageMapId)
    .def("setLoopClosureId", &Statistics::setLoopClosureId)
    .def("setLoopClosureMapId", &Statistics::setLoopClosureMapId)
    .def("setProximityDetectionId", &Statistics::setProximityDetectionId)
    .def("setProximityDetectionMapId", &Statistics::setProximityDetectionMapId)
    .def("setStamp", &Statistics::setStamp)

    .def("addSignatureData", &Statistics::addSignatureData)
    .def("setSignaturesData", &Statistics::setSignaturesData)

    .def("setPoses", &Statistics::setPoses)
    // .def("setConstraints", &Statistics::setConstraints)
    .def("setMapCorrection", &Statistics::setMapCorrection)
    .def("setLoopClosureTransform", &Statistics::setLoopClosureTransform)
    .def("setLocalizationCovariance", &Statistics::setLocalizationCovariance)
    .def("setLabels", &Statistics::setLabels)
    .def("setWeights", &Statistics::setWeights)
    .def("setPosterior", &Statistics::setPosterior)
    .def("setLikelihood", &Statistics::setLikelihood)
    .def("setRawLikelihood", &Statistics::setRawLikelihood)
    .def("setLocalPath", &Statistics::setLocalPath)
    .def("setCurrentGoalId", &Statistics::setCurrentGoalId)
    .def("setReducedIds", &Statistics::setReducedIds)
    .def("setWmState", &Statistics::setWmState)
    .def("setOdomCachePoses", &Statistics::setOdomCachePoses)
    // .def("setOdomCacheConstraints", &Statistics::setOdomCacheConstraints)

    .def("extended", &Statistics::extended)
    .def("refImageId", &Statistics::refImageId)
    .def("refImageMapId", &Statistics::refImageMapId)
    .def("loopClosureId", &Statistics::loopClosureId)
    .def("loopClosureMapId", &Statistics::loopClosureMapId)
    .def("proximityDetectionId", &Statistics::proximityDetectionId)
    .def("proximityDetectionMapId", &Statistics::proximityDetectionMapId)
    .def("stamp", &Statistics::stamp)

    .def("getLastSignatureData", &Statistics::getLastSignatureData)
    .def("getSignaturesData", &Statistics::getSignaturesData)

    .def("poses", &Statistics::poses)
    // .def("constraints", &Statistics::constraints)
    .def("mapCorrection", &Statistics::mapCorrection)
    .def("loopClosureTransform", &Statistics::loopClosureTransform)
    .def("localizationCovariance", &Statistics::localizationCovariance)
    .def("labels", &Statistics::labels)
    .def("weights", &Statistics::weights)
    .def("posterior", &Statistics::posterior)
    .def("likelihood", &Statistics::likelihood)
    .def("rawLikelihood", &Statistics::rawLikelihood)
    .def("localPath", &Statistics::localPath)
    .def("currentGoalId", &Statistics::currentGoalId)
    .def("reducedIds", &Statistics::reducedIds)
    .def("wmState", &Statistics::wmState)
    .def("odomCachePoses", &Statistics::odomCachePoses)
    // .def("odomCacheConstraints", &Statistics::odomCacheConstraints)

    .def("data", &Statistics::data);
}