from typing import overload


class Odometry:
    @overload
    def process(self, arg0: "rtabmap::SensorData", arg1: "rtabmap::OdometryInfo", /) -> "rtabmap::Transform": ...

    @overload
    def process(self, arg0: "rtabmap::SensorData", arg1: "rtabmap::Transform", arg2: "rtabmap::OdometryInfo", /) -> "rtabmap::Transform": ...

    def reset(self, arg: "rtabmap::Transform", /) -> None: ...

    def getType(self) -> "rtabmap::Odometry::Type": ...

    def canProcessRawImages(self) -> bool: ...

    def canProcessAsyncIMU(self) -> bool: ...

def add(a: int, b: int) -> int: ...
